export const images = {
  hero: "/images/hero-bartender.jpg",
  heroCraft: "/images/hero-bar-craft.jpg",
  heroNight: "/images/hero-dj-crowd.jpg",
  tapRoom: "/images/experience-tap-room.jpg",
  mixology: "/images/experience-mixology.jpg",
  spiritBar: "/images/experience-spirit-bar.jpg",
  about: "/images/about-cocktails.jpg",
  story: "/images/story-bar.jpg",
  storyPillOne: "/images/pill-citrus.jpg",
  storyPillTwo: "/images/pill-pour.jpg",
  storyPillThree: "/images/pill-glass.jpg",
  gallery: [
    "/images/gallery-01.jpg",
    "/images/gallery-02.jpg",
    "/images/gallery-03.jpg",
    "/images/gallery-04.jpg",
    "/images/gallery-05.jpg",
  ],
  hours: "/images/hours-lounge.jpg",
  menu: "/images/menu-cocktail.jpg",
  contact: "/images/contact-lounge.jpg",
  footer: "/images/footer-lounge.jpg",
  texture: "/images/texture-barrel.jpg",
  avatars: [
    "/images/avatar-01.jpg",
    "/images/avatar-02.jpg",
    "/images/avatar-03.jpg",
  ],
  dishes: {
    crostini: "/images/dish-crostini.jpg",
    oyster: "/images/dish-oyster.jpg",
    tartare: "/images/dish-tartare.jpg",
    marrow: "/images/dish-marrow.jpg",
    wagyu: "/images/dish-wagyu.jpg",
    risotto: "/images/dish-risotto.jpg",
    ribeye: "/images/dish-ribeye.jpg",
    scallops: "/images/dish-scallops.jpg",
    chocolate: "/images/dish-chocolate.jpg",
    panna: "/images/dish-panna.jpg",
    tart: "/images/dish-tart.jpg",
    oldfashioned: "/images/dish-oldfashioned.jpg",
    negroni: "/images/dish-negroni.jpg",
    smoke: "/images/dish-smoke.jpg",
    martini: "/images/dish-martini.jpg",
  },
} as const;
